server:
    port: 8040
spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/constech2
        username: postgres
        password: admin
    jpa:
        database: postgresql
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
    h2:
        console:
            enabled: true
            path: /h2-console
            settings:
                trace: false
                web-allow-others: false

documentation:
    application:
        description: project.description@
        version: project.version@

pringdoc:
    # Contract endpoint: http://localhost:8040/v3/api-docs
    api-docs:
        path: /api-docs
    # Documentation endpoint: http://localhost:8040/swagger-ui/index.html
    swagger-ui:
        path: /swagger-ui/index.html

